name: Create Infra and Launch Traffic

on:
  workflow_dispatch:

jobs:
  crate_infra_and_launch_traffic:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Get ALB Name from Terraform Output
        id: get_alb_name
        run: |
          ALB_DNS=$(terraform output -raw alb-dns-name)
          echo "✅ ALB DNS: $ALB_DNS"
          echo "ALB_URL=http://$ALB_DNS" >> $GITHUB_ENV
      - name: Wait 60seconds for Instances to Warm up and  start sending Traffic
        run: sleep 60

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install requests
      - name: Launch Bot Traffic
        run: |
          source venv/bin/activate
          python3 bot_traffic.py
